-- AlterEnum
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'PICKUP_CANCELLED';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'DUPLICATE';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'ALREADY_SUBMITTED_TO_PWC_OFFICE';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'PWC_CONFIRMATION_AWAITED';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'GATEPASS_PENDING';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'ALIGN_FOR_PICKUP';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'IN_TRANSIT';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'ON_HOLD';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'RTO_CASE';
ALTER TYPE "ReversePickupStatus" ADD VALUE IF NOT EXISTS 'LOST_DEVICE';
